---
title: "Brownlows Bets"
author: "Put your name here!"
date: "put the date here"
output: html_document: default
 ---

<!-- We recommend you use git branches -- create a separate branch for each major section i.e. Introduction, Methods, Results, Inferential Results, and Discussion and Conclusions - leave the YAML block untouched until the final merge where you put in your own name !-->

# Introduction

<!--In this section you explain what you are trying to show.  Where did the data come from?  What is the research or other question you are trying to answer?!-->

 At the first day of class there are 35 students in Math Statistics class and professor Brownlow always proposes this bet to his students "I will wager $2 to your bet of $1 that at least two people in today's class have  the same birthday.  He tells me he has made that bet 1137 times so far. Where do you think his profits are? Discuss this in a markdown document

# Methods

<!--Decide on your methods:  In this section explain the approach you will take to attack the issue --- how will you decide on a likely estimate of professor Brownlow's earnings or losses after 1137 bets. Also explain how you construct a 95% confidence interval about your estimate of his winnings !-->

We will aproach this problem through a sequence of simulations. first we will let the numbers from 1 to 365 represent the different possible Bdays a student could have(1 would be Jan. 1st, 32would be Feb. 1st etc). Then we will randamly select(with replacement to insure two of the same number could be choosen)35 numbers to represent the same class. Then we need to examen the numbers choosen to see if any are duplicates (a duplicate would repersent two people with the same Bday). if there is a duplicate we will give Borwnlow 1 dollar for this bet. If not we will take 2 dollars away from him. We Will do the same procedure 1137 times. In the end we will totalhis winnings and loosings and we will use that number as an estimate of his take-home.

#Profit Estimate

<!--Explain and display the results of your method of coming up with the estimate of professor Brownlows betting!-->


# Confidence interval of Brownlows earning

<!--Explain and display your method of coming up with a 95% confidence interval of  professor Brownlows-->


# Discussion and Conclusion

<!--Discussion and conclusion here.  If professor Brownlow is consistantly making or losing money how could he change his payout so that his profits center on zero?  Also discuss what size his class should be in order to have his current scheme balance at zero profit.!-->

